---
- name: "install log2ram"
  hosts: "all"
  become: true
  become_user: "root"
  vars:
    blacklist_file: "/etc/modprobe.d/blacklist-dvb.conf"
  tasks:
    - name: blacklist existing sdr module
      copy:
        dest: "{{ blacklist_file }}"
        content: |
          blacklist dvb_usb_rtl28xxu
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "Ansible apt install sdr deps"
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - "rtl-sdr"
        - "libtool"
        - "libusb-1.0-0-dev"
        - "librtlsdr-dev"
        - "build-essential"
        - "cmake" 
        - "pkg-config"
        - "ninja-build"
        - "git"