# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
# playbook to update any installed package
# remove any unused packages
# and reboot system if needed
---
- name: Update OS packages reboot if kernel update
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache.
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Upgrade all packages on servers.
      apt:
        upgrade: dist
    - name: Remove useless packages from the cache
      apt:
        autoclean: true
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: true
    - name: Check if a reboot is needed on all servers.
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 10
        test_command: uptime
      when: reboot_required_file.stat.exists
