---
- name: "resize default console font size"
  hosts: "all"
  become: true
  become_user: "root"
  vars:
    config_file: "/etc/default/console-setup"
  tasks:
    - name: "replace font face."
      ansible.builtin.replace:
        path: "{{ config_file }}"
        regexp: "^FONTFACE=.*$"
        replace: 'FONTFACE="TerminusBold"'
    - name: "replace font size."
      ansible.builtin.replace:
        path: "{{ config_file }}"
        regexp: "^FONTSIZE=.*$"
        replace: 'FONTSIZE="16x32"'
