# TODO complete config for unattended upgrades
# https://www.reddit.com/r/Ubuntu/comments/15uwy95/updating_ubuntu_unattended/
# https://www.digitalocean.com/community/tutorials/how-to-keep-ubuntu-20-04-servers-updated
# https://phoenixnap.com/kb/automatic-security-updates-ubuntu
---
- name: "setup unattended upgrades and needrestart"
  hosts: "all"
  become: true
  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "install deps"
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - "unattended-upgrades"
        - "needrestart"
    - name: deploy auto resrtart conf
      copy:
        src: "{{ playbook_dir }}/../../etc/needrestart/conf.d/auto.conf"
        dest: /etc/needrestart/conf.d/auto.conf
        owner: root
        group: root
        mode: 0644
    - name: Restart service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: "{{ item }}"
      loop:
        - "unattended-upgrades"