---
- name: "set ntp timesyncd"
  hosts: "all"
  become: true
  tasks:
    - name: "Create dispatcher.d directory if it does not exist"
      ansible.builtin.file:
        path: "/etc/NetworkManager/dispatcher.d"
        state: "directory"
        mode: "0755"
    - name: "deploy dispatcher script"
      ansible.builtin.copy:
        src: "/mnt/clones/data/etc/NetworkManager/dispatcher.d/05-dhcp-timesyncd"
        dest: "/etc/NetworkManager/dispatcher.d/05-dhcp-timesyncd"
        owner: "root"
        group: "root"
        mode: "0755"
