---
- name: "set policy kit overrides"
  hosts: "all"
  become: true
  become_user: "root"
  tasks:
    - name: "deploy policy kit orverride colord"
      ansible.builtin.copy: null
      src: "/mnt/clones/data/etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla"
      dest: "/etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla"
      owner: "root"
      group: "root"
      mode: "0755"
    - name: "deploy policy kit orverride apt"
      ansible.builtin.copy: null
      src: "/mnt/clones/data/etc/polkit-1/localauthority/50-local.d/46-allow-apt.pkla"
      dest: "/etc/polkit-1/localauthority/50-local.d/46-allow-apt.pkla"
      owner: "root"
      group: "root"
      mode: "0755"
    - name: "deploy policy kit orverride reboot"
      ansible.builtin.copy: null
      src: "/mnt/clones/data/etc/polkit-1/localauthority/50-local.d/47-allow-reboot.pkla"
      dest: "/etc/polkit-1/localauthority/50-local.d/47-allow-reboot.pkla"
      owner: "root"
      group: "root"
      mode: "0755"
    - name: "reload and Restart polkitd"
      ansible.builtin.systemd_service:
        state: "restarted"
        daemon_reload: true
        name: "polkitd"
