---
- name: "Lockdown ssh configs"
  hosts: "all"
  become: true
  vars:
    config_file: "/etc/ssh/sshd_config.d/lockdown.conf"
    multiline: |
          PubkeyAuthentication yes
          PasswordAuthentication no
          PermitRootLogin no
          PermitEmptyPasswords no
          ChallengeResponseAuthentication yes        

  tasks:
    - name: reset sshd config
      ansible.builtin.copy:
        src: /usr/share/openssh/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
    - name: "lockdown ssh"
      copy:
        dest: "{{ config_file }}"
        content: "{{ multiline }}"
    - name: "restart  sshd"
      systemd:
        state: "restarted"
        daemon_reload: true
        name: "ssh.service"
