# https://github.com/docker/docker-install/
---
- name: "install docker via official install script"
  hosts: "all"
  become: true
  vars:
    user_name: "tcronin"
  tasks:
    - name: "Remove any legacy docker libs"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "absent"
      loop:
        - "docker.io"
        - "docker-compose"
        - "docker-compose-v2"
        - "docker-doc"
        - "podman-docker"
    - name: "Download docker install script"
      ansible.builtin.get_url:
        url: "https://get.docker.com"
        dest: "/tmp/get-docker.sh"
        mode: "0755"
        force: true
    - name: "Run docker install script"
      ansible.builtin.command:
        cmd: "sh /tmp/get-docker.sh"
        creates: "/usr/bin/docker"
    - name: "Remove docker install script"
      ansible.builtin.file:
        path: "/tmp/get-docker.sh"
        state: "absent"
    - name: "adding existing user '{{ user_name }}' to group docker"
      ansible.builtin.user:
        name: "{{ user_name }}"
        groups: "docker"
        append: true
