---
- name: "initialize packages for laptop"
  hosts: "all"
  become: true
  become_user: "root"
  vars:
    node_ver: 22
  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "Ansible apt install base deps"
      apt:
        name: "curl"
        state: "present"
    - name: "add node js repo"
      block:
        - name: "get node script"
          ansible.builtin.get_url:
            url: "https://deb.nodesource.com/setup_{{ node_ver }}.x"
            dest: "/tmp/nodesource_setup.sh"
            mode: "0700"
            force: true
        - name: "run script"
          command: "bash -c '/tmp/nodesource_setup.sh'"
    - name: "Update apt added repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "apt install nodejs"
      apt:
        name: "nodejs"
        state: "present"
