# https://community.hailo.ai/t/new-release-4-18-raspberry-pi-ai-kit-now-with-hailo-python-api-support-clip-zero-shot-classification-and-picamera2-examples/3072
---
- name: "add python libs and dependencies"
  hosts: "all"
  become: true
  become_user: "root"
  vars:
    env_file: "/etc/environment"
  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "Ansible apt install base deps"
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - "python3-dev"
        - "python3-setuptools"
        - "python3-wheel"
        - "python3-venv"
        - "pipx"
        - "git"
        - "build-essential" 
        - "cmake" 
        - "libavcodec-dev" 
        - "libavformat-dev" 
        - "libswscale-dev"
        - "libgstreamer-plugins-base1.0-dev"
        - "libgstreamer1.0-dev" 
        - "libgtk-3-dev"
        - "libpng-dev"
        - "libjpeg-dev" 
        - "libopenexr-dev" 
        - "libtiff-dev" 
        - "libwebp-dev"
        - "libopencv-dev" 
        - "x264" 
        - "libx264-dev" 
        - "libssl-dev" 
        - "ffmpeg"
    - name: "install picamera2"
      ansible.builtin.apt:
        name: python3-picamera2
        state: latest
        install_recommends: no
    - name: "add poetry envars"
      blockinfile:
        state: "present"
        insertafter: "EOF"
        dest: "{{ env_file }}"
        marker: "# {mark} _POETRY"
        append_newline: true
        prepend_newline: true
        block: |
          POETRY_VIRTUALENVS_IN_PROJECT=true
          POETRY_VIRTUALENVS_OPTIONS_SYSTEM_SITE_PACKAGES=true
