---
- name: "install dbeaver"
  hosts: "all"
  become: true
  tasks:
    - name: "add repo"
      ansible.builtin.apt_repository:
        repo: ppa:serge-rider/dbeaver-ce
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "install"
      apt:
        name: "dbeaver-ce"
        state: "present"
