# https://github.com/astrada/google-drive-ocamlfuse
# https://www.baeldung.com/linux/google-drive-guide
# requires oauth 2 sign on
---
- name: "install gdrive fs"
  hosts: "all"
  become: true
  tasks:
    - name: "add repo"
      ansible.builtin.apt_repository:
        repo: ppa:alessandro-strada/ppa
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "install"
      apt:
        name: "google-drive-ocamlfuse"
        state: "present"
