---
- name: "install libraoffice"
  hosts: "all"
  become: true
  tasks:
    - name: "add repo"
      ansible.builtin.apt_repository:
        repo: ppa:libreoffice/ppa
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "install"
      apt:
        name: "libreoffice"
        state: "present"
