---
- name: "initialize packages for work laptop"
  hosts: "all"
  become: true
  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "Ansible apt install base deps"
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - "curl"
        - "gnupg"
        - "gpg"
        - "wget"
        - "snapd"
    - name: "add and sign wine repo"
      block:
        - name: "wine repo key"
          ansible.builtin.get_url:
            url: "https://dl.winehq.org/wine-builds/winehq.key"
            dest: "/etc/apt/keyrings/winehq-archive.key"
            mode: "0644"
            force: true
        - name: "wine repo source"
          ansible.builtin.get_url:
            url:
              "https://dl.winehq.org/wine-builds/ubuntu/dists/{{ ansible_distribution_release\
              \ }}/winehq-{{ ansible_distribution_release }}.sources"
            dest: "/etc/apt/sources.list.d/winehq-{{ ansible_distribution_release }}.sources"
            mode: "0644"
            force: true
        - name: "Update apt repo and cache."
          apt:
            update_cache: true
            cache_valid_time: 3600
    - name: "Update apt added repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "apt install wine deps"
      apt:
        name: "{{ item }}"
        install_recommends: true
        state: "present"
      loop:
        - "wine"
        - "wine-stable"
        - "winetricks"
    - name: "Install snap deps"
      community.general.snap:
        name:
          - "wine-platform-runtime-core20"
