---
- name: "copy motd script"
  hosts: "all"
  become: true
  tasks:
    - name: deploy motd
      copy:
        src: "{{ playbook_dir }}/../../etc/profile.d/motd.sh"
        dest: /etc/profile.d/motd.sh
        owner: root
        group: root
        mode: 0644
