---
- name: "install letsincrypt certbot"
  hosts: "all"
  become: true
  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "Remove deprecteded cerbot"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "absent"
      loop:
        - "certbot"
    - name: "install snapd"
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - "snap"
    - name: Install deps
      community.general.snap:
        name: core
    - name: Install certbot
      community.general.snap:
        name: certbot
        classic: true
    - name: link
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        owner: root
        group: root
        state: link
        mode: '0755'