---
- name: "install helm"
  hosts: "all"
  become: true
  become_user: "root"
  vars:
    helm_version: "3.15.2"
  tasks:
    - name: "download n unarchive"
      ansible.builtin.unarchive:
        src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-arm.tar.gz"
        dest: /tmp
        owner: root
        group: root
        mode: 0755
        remote_src: yes
    - name: "copy helm to bin"
      ansible.builtin.copy:
        src: "/tmp/linux-arm/helm"
        dest: "/usr/local/bin/helm"
        remote_src: true
        mode: "0777"
    - name: "Delete archive"
      ansible.builtin.file:
        path: "/tmp/helm-linux-arm.tar.gz"
        state: "absent"
    - name: "Delete folder"
      ansible.builtin.file:
        path: "/tmp/linux-arm"
        state: "absent"
