---
- name: "install influx cli"
  hosts: "all"
  become: true
  vars:
    influx_ver: "2.7.5"
  tasks:
    - name: "download n install"
      ansible.builtin.unarchive:
        src: "https://dl.influxdata.com/influxdb/releases/influxdb2-client-{{ influx_ver }}-linux-arm64.tar.gz"
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755
        remote_src: yes
    - name: "Delete readme"
      ansible.builtin.file:
        path: "/usr/local/bin/README.md"
        state: "absent"
    - name: "Delete license"
      ansible.builtin.file:
        path: "/usr/local/bin/LICENSE"
        state: "absent"

