alias cls='printf "\033c"'
alias ssdtemp="sudo smartctl -a /dev/nvme0n1 | egrep '^Temperature:' | sed -E 's/.*([0-9]{2})\s+(\w*)/\1 \2/'"
alias listsvc='systemctl list-unit-files --type=service'
alias listenable='systemctl list-unit-files --type=service --state=enabled'
alias gitclean='git fetch; git reflog expire --expire=now --all; git gc --prune=now; git remote prune origin; git fsck --full'
alias flushdns='sudo resolvectl flush-caches && sudo ip route flush cache'
alias flusharp='sudo ip -s -s neigh flush all'
alias flushnet='sudo ip -s -s neigh flush all && sudo resolvectl flush-caches && sudo ip route flush cache && sudo systemctl restart NetworkManager'
alias pwdany='head -c 512 /dev/urandom  | tr -dc [:graph:] |  head -c 12'
alias pwdalnu='head -c 512 /dev/urandom  | tr -dc [:alnum:] |  head -c 12'
alias tokengen='openssl rand -base64 48'
alias netconf='resolvectl status'
alias netdev='sudo lshw -c network'
alias clpreset='sudo pkill -f VBoxClient && sudo VBoxClient --clipboard'