---
- name: "install pritunl vpn client"
  hosts: "all"
  become: true
  tasks:
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "Ansible apt install base deps"
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - "gnupg"
        - "gpg"
    - name: "remove apt src"
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/pritunl.list"
        state: "absent"
    - name: "add apt source"
      copy:
        dest: "/etc/apt/sources.list.d/pritunl.list"
        content:
          "deb https://repo.pritunl.com/stable/apt oracular main"
    - name: "add key"
      command:
        "gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A"
    - name: "export key"
      command:
        "bash -c 'gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A | tee /etc/apt/trusted.gpg.d/pritunl.asc'"
    - name: "Update apt added repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "apt install prit client"
      apt:
        name: "pritunl-client-electron"
        state: "present"
