---
- name: "initialize packages for openvpn client"
  hosts: "all"
  become: true
  become_user: "root"
  tasks:
    - name: "add and sign docker repo"
      block:
        - name: "repo key"
          ansible.builtin.get_url:
            url: "https://packages.openvpn.net/packages-repo.gpg"
            dest: "/etc/apt/keyrings/openvpn.asc"
            mode: "0644"
            force: true
        - name: "apt source"
          ansible.builtin.apt_repository:
            repo:
              "deb [signed-by=/etc/apt/keyrings/openvpn.asc] https://packages.openvpn.net/openvpn3/debian\
              \ {{ ansible_distribution_release }} main"
            filename: "openvpn"
            state: "present"
            update_cache: true
        - name: "Update apt added repo and cache."
          apt:
            update_cache: true
            cache_valid_time: 3600
        - name: "apt install openvpn"
          apt:
            install_recommends: true
            name: "{{ item }}"
            state: "present"
          loop:
            - "openvpn"
            - "openvpn-systemd-resolved"
