# https://rclone.org/downloads/
# https://go.dev/wiki/Ubuntu
---
- name: "install rclone cli"
  hosts: "all"
  become: true
  tasks:
    - name: "add go repo"
      ansible.builtin.apt_repository:
        repo: ppa:longsleep/golang-backports
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "install"
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - "golang-go"
        - "unzip"
    - name: "get rclone installer"
      ansible.builtin.get_url:
        url: "https://rclone.org/install.sh"
        dest: "/tmp/rclone-install.sh"
        mode: "0700"
        force: true
    - name: "install rclone"
      ansible.builtin.shell: 
        executable: /bin/bash
        cmd: "/tmp/rclone-install.sh"
    # https://www.jeffgeerling.com/blog/2017/add-path-global-path-ansible
    # - name: update path.
    #   copy:
    #     dest: /etc/profile.d/rclone-path.sh
    #     content: 'PATH=$PATH:/opt/rclone'
