# https://rclone.org/downloads/
# https://go.dev/wiki/Ubuntu
---
- name: "install rclone cli"
  hosts: "all"
  become: true
  tasks:
    # the built in apt_repository uses the legacy keyring
    - name: "add go repo"
      ansible.builtin.command: add-apt-repository -y ppa:longsleep/golang-backports
      args:
        creates: /etc/apt/sources.list.d/longsleep-ubuntu-golang-backports-{{ ansible_distribution_release }}.list
    - name: "Update apt repo and cache."
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "install"
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - "golang-go"
        - "unzip"
    - name: "get rclone installer"
      ansible.builtin.get_url:
        url: "https://rclone.org/install.sh"
        dest: "/tmp/rclone-install.sh"
        mode: "0700"
        force: true
    - name: "install rclone"
      ansible.builtin.shell: 
        executable: /bin/bash
        cmd: "/tmp/rclone-install.sh"
